//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::app_user::Entity as AppUser;
pub use super::club::Entity as Club;
pub use super::slot::Entity as Slot;
pub use super::zone::Entity as Zone;
